sequenceDiagram
    participant browser
    participant server

    browser->>browser: Update list locally

    browser->>browser: Rerender note list

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa
    Note right of browser: The request comes with the JSON data of the Content and Date
